### ISSUE TITLE
ECS GPU ARM  AMI for Amazon EC2 G5g instances

### ISSUE THREAD

**Issue by gmarchand** [aws/amazon-ecs-ami#241] opened 2024-05-07 16:10 UTC
### Summary
Support the Amazon EC2 G5g instances 
Today AWS ECS GPU AMI only support `Amazon Linux AMI 2.0.${var.ami_version_al2} x86_64 ECS HVM GP2` and not ARM

### Description

Amazon EC2 G5g instances are powered by AWS Graviton2 processors and feature NVIDIA T4G Tensor Core GPUs
https://aws.amazon.com/ec2/instance-types/g5g/?nc1=h_ls

**Comment by sparrc** [comment] 2024-05-07 21:34
dupe of https://github.com/aws/amazon-ecs-ami/issues/220, 

> thank you for the feature request, the ECS team can support this instance type as soon as we have available ARM NVIDIA packages in the AL2023 yum repos. If you'd like the Amazon Linux team to consider adding ARM NVIDIA packages in addition to x86, I suggest you add your feedback to this ticket here: https://github.com/amazonlinux/amazon-linux-2023/issues/12

> I think it's unlikely that ARM NVIDIA packages will be added to AL2, but for AL2023 we are also hoping this request is delivered :)

**Closed by sparrc** 2024-05-07 21:34 UTC
